consensus/byzantine_test.go
consensus/state.go
consensus/state_test.go

As in title. I have added a test for this case, I will need to flesh it out further since it is a little hacky and doesn't cover the other cases in doPrevote that should be tested it looks like.
When I do this slot protocol, I will add a test that the block is rejected if the slot protocol is unhappy, plus a test that the block is rejected if it does/nt contain entropy in line with the entropy generator

Add check/reject for tx strictness

---

mempool/clist_mempool.go

I saw this in the end to end test:
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0xccebae]
goroutine 165 [running]:
github.com/tendermint/tendermint/mempool.(*CListMempool).GetNewTxs(0xc0003409c0, 0x2, 0x64, 0x7fb7917f4308, 0xc000aff380, 0x1)
/home/runner/work/cosmos-consensus/cosmos-consensus/mempool/clist_mempool.go:501 +0x76e
github.com/tendermint/tendermint/mempool.(*Reactor).broadcastTxRoutine(0xc000117b90, 0x1370020, 0xc000440d80)
/home/runner/work/cosmos-consensus/cosmos-consensus/mempool/reactor.go:239 +0x3da
created by github.com/tendermint/tendermint/mempool.(*Reactor).AddPeer
/home/runner/work/cosmos-consensus/cosmos-consensus/mempool/reactor.go:151 +0x53
```
So I think this should fix …

catch possible segv when accessing front of queue in mempool

---

beacon/entropy_generator.go

Computation of aeon length in block header was out by one as aeon.Start and aeon.End are both inclusive.

Fix aeon length in block header

---

beacon/common_test.go
beacon/dkg.go
beacon/dkg_runner.go
beacon/dkg_runner_test.go
beacon/dkg_test.go
beacon/slot_protocol_enforcer.go
beacon/slot_protocol_enforcer_test.go
consensus/common_test.go
consensus/reactor_test.go
consensus/state.go
mempool/clist_mempool.go
mempool/clist_mempool_test.go
node/node.go
node/node_test.go
types/dkg_messages.go

slot protocol enforcer: will not let dkg txs into the mempool if they are a duplicate for that dkgID, dkgIteration. 'Future' dkg messages are witheld for a short period to account for someone sending you a dkg message before you have started your dkg (and would assume it to be invalid).
To do this, in short the DKG enforcer keeps a pointer to the dkg so it can check messages against.
Blocks might still contain duplicates/stale messages, but these are not 'voted down' as I originally intended. This is as it would make it more error prone to do this: if there was a crash that made you clear your known slots, you might be submitting a block that the rest of the network considers invalid.
Unfortunetly to avoid a circular dependency the way the mempool handles it is using callbacks which is …

Introduce slot protocol enforcer

---

blockchain/v1/reactor_test.go

Saw test failure on security branch:
```
panic: failed to process committed block (4:612B091B60A96F35C691CB84C13F2496648F9ABD55A640B06B4CC4745112C3BA): wrong Block.Header.LastBlockID.  Expected 9038EC2293882A51270A941C96F934933EBC197E03ECD1C84E2B52678F273983:1:0B78D6DA2B47, got D16C5201218C11D313CAE92D4C0C26E81F737E69AE2BC0E2AD0D677D8706F26D:1:78A9CFAC3CCC
goroutine 447 [running]:
github.com/tendermint/tendermint/blockchain/v1.(*BlockchainReactor).processBlock(0xc000b8e700, 0xc0010e3efc, 0x3)
/home/runner/work/cosmos-consensus-security/cosmos-consensus-security/blockchain/v1/reactor.go:434 +0x764
github.com/tendermint/tendermint/blockchain/v1.(*BlockchainReactor).processBlocksRoutine(0xc000b8e700, 0xc00008e7e0)
/home/runner/work/cosmos-consensus-security/cosmos-consensus-security/blockchai …
```

Fix flakey blockchain v1 test

---

mempool/clist_mempool.go
mempool/metrics.go

Add counters which distuingish between txs arriving and txs verified. This will give a hint if the txs are arriving in bulk but are taking a long time to process/verify which is a bottleneck

metrics that have counters for the size of the txs that have arrived

---

beacon/entropy_generator.go

Bug fix from deployment. Entropy generator now checks that keys in files are not out of order, and returns error on creation of node if they are. Adding of new items of into next aeon queue also prevents older keys from being pushed onto the queue.

Prevent out of order next aeon queue

---

beacon/entropy_generator.go
consensus/state.go
consensus/state_test.go
types/entropy_share.go

Allow consensus validators to be a subset of the entropy validators so that jailed validators can be removed from the consensus validators.

Allow consensus to be updated with jailed validators

---

mempool/clist_mempool.go
mempool/clist_mempool_test.go

Bug fix to allow appending of dkg txs to peerPointer. Removed filtering of priority txs in GetNewTxs when getting transactions from main txs queue.

Bug fix add txs to peer priority txs

---

beacon/aeon_details.go
beacon/entropy_generator.go

- Impose a limit on the number of next aeon keys since in normal operation (not during syncing) the dkg is only computed one ahead of the current aeon. 
- Add finaliser to free C++ BaseAeon when aeonDetails is deleted

Limit next aeon key queue

---

beacon/entropy_generator.go

Fetch dkg validators rather than consensus validators when loading keys from file in entropy generator

Fetch dkg vals in entropy gen load keys

---

config/config.go

Revert this as it breaks fetchd tests

don't strict filter by default

---

config/config.go

This reverts commit 7c21c84f2c67f27e86dedfa60cf95473c6d91179.

Revert "don't strict filter by default (#193)"

---

beacon/aeon_details.go

- Add validator height and dkg id to all saved keys and always validate these fields

Fix saving of keyless aeon to file and validation

---

beacon/dkg.go

Changes made so that DKG waits to receive its own dkg encryption key through blocks. This ensures that all nodes fail the DKG at the same stage and evidence generation correctly reflects the dkg failure.

Wait for own encryption key

---

blockchain/v1/reactor_test.go
consensus/common_test.go
consensus/state.go
consensus/state_test.go
consensus/types/height_vote_set_test.go
lite2/client.go
lite2/helpers_test.go
lite2/verifier.go
state/validation_test.go
types/test_util.go
types/validator_set.go
types/validator_set_test.go
types/vote.go
types/vote_set.go

- Prepend the concatenation of chain ID and validator set hash to votes before signing
- Acts as gtag in combined signature

Prepend validator set hash to vote

---

types/block.go
types/block_test.go
types/test_util.go

- When reconstructing commit to vote, forcefully add votes which do not contain timestamp signatures

Allow commit to vote set conversion without timestamp sigs

---

consensus/reactor.go
consensus/state.go
rpc/client/rpc_test.go
types/canonical.go
types/vote.go

- Verify timestamp in commit votes using timestamps seen locally
- Always gossip precommit messages to avoid stalling due to unseen timestamps
- Sign timestamp with vote to avoid timestamp signature being re-used to different vote message

Block vote timestamp verification

---

consensus/reactor.go
consensus/timestamp_test.go
consensus/types/height_vote_set.go
consensus/types/peer_round_state.go
types/precommit_set.go

- Fix failed interface conversion from return of nil interface in height vote set getPrecommit and getPrevote
- Fix race condition in getting validator set size in consensus/reactor log message. Save validator set size in creation of PrecommitRecord instead
- Fix incorrect signing of votes in timestamp test

Fix race and nil return in precommits/votes

---

blockchain/v1/reactor_test.go
consensus/reactor.go
store/store.go

- Fetch commits seen (which includes timestamp signature) rather than block commits when gossiping to peers
- When saving block at height H, trim the seen commits at height H-1 to only contain those included in the block at height H
- Fix blockchain test so that it computes seenCommit for block height 1

Bug fix in commit gossip and trim commits in store

---

crypto/bls12_381/bls12_381.go
lite2/client.go
lite2/client_benchmark_test.go
lite2/helpers_test.go
lite2/verifier.go
types/validator_set.go
types/validator_set_test.go

- Remove validation of vote signature in light client and replace with combined signature verification

Verify combined signature in light client

---

beacon/crypto_test.go
mcl_cpp/combined_sigs.cpp
mcl_cpp/combined_sigs.hpp
types/block.go
types/validator_set.go
types/validator_set_test.go

- Reduce number of string to mcl type conversions to improve performance of combined signatures
- Add benchmarks for combined sig and block verification functions

Benchmarking combined sigs

---

lite2/client_benchmark_test.go
types/validator_set.go

Client was not reset in between runs and therefore in later runs was already synced with block 1000. Also, minor modifications to block verification.

Fix light client bisection benchmark
